version: '3'

services:
  kafka:
    image: 'bitnami/kafka:3.3.1'
    #Uncomment if you want to test it our from outside container.
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=lbX5g8wuS22UON89iYM65w
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=EXTERNAL://0.0.0.0:9092,CLIENT://:9099,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092,CLIENT://kafka:9099
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka-ui:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka:9099
      - SERVER_SERVLET_CONTEXTPATH=/

  schema-registry:
    image: apicurio/apicurio-registry-mem:2.3.1.Final
    ports:
      - 8081:8080
    depends_on:
      - kafka
    environment:
      QUARKUS_PROFILE: prod